#!/usr/bin/env ruby
puts "*** Hey #{ENV['USER']} I'll try to generate Swagger definitions for you.."

require 'yaml'

# Helpers

def decimal(hex_string)
  hex_string.to_i(16)
end

def ieee(hex_string)
  [hex_string.gsub('0x', '')].pack('H16').unpack('g').first
end

def hex_to_s(hex_string)
  [hex_string.gsub('0x', '')].pack('H*')
end

def swagger_name(name)
  name.split('_').map { |w| w.capitalize }.join
end

def swagger_prop_name(spec)
  return spec['title_case_name'] if spec['title_case_name']

  spec['name'].split('_').map.with_index { |w, i| 
    i == 0 ? w : w.capitalize
  }.join
end

# Create header
defs = Hash.new
defs['definitions'] = Hash.new

# Load exceptions spec
exceptions = YAML.load_file('exceptions.yaml')

# All capabilities
Dir.glob('../*.yml') do |yml_file|
  # Capability
  spec = YAML.load_file(yml_file)
  
  if exceptions['rejections'].include?(spec['name'])
    puts "Skipping #{spec['name']} as it should be rejected.."
    next  
  elsif not spec['properties']
    puts "Skipping #{spec['name']} as there's no properties.."
    next
  end

  cap = Hash.new
  cap['type'] = 'object'
  cap['properties'] = Hash.new
  cap_name = nil

  example = YAML.load_file("../examples/#{spec['name']}.yml")

  # - Get Swagger formatted model name
  spec['message_types'].each do |msg|
    if msg['id'] == '0x01'
      cap_name = swagger_name(msg['name'])
      break
    end
  end

  puts "Starting with #{cap_name}.."

  # - Capability properties
  spec['properties'].each do |prop_spec|
    puts "Now property #{prop_spec['name']}.."
    prop = Hash.new

    # --- Check for swagger exception
    if ex_item = exceptions['exceptions'][prop_spec['name']]
      puts "Found an exception for exception #{ex_item}.."
      prop = ex_item.dup
    else
      example_val = example[prop_spec['name']] ?
        example[prop_spec['name']].first['item'].first['value'] : String.new

      case prop_spec['type']
      when 'string'
        prop['type'] = 'string'
        # -- Handling string format
        prop['example'] = 'TODO' # TODO: hex_to_s(example_val)
        prop['description'] = prop_spec['description']
      when 'integer'
        prop['type'] = 'number'
        prop['format'] = 'integer'
        # -- Handling decimal format
        prop['example'] = decimal(example_val)
        prop['description'] = prop_spec['description']
      when 'float', 'double' # TODO: test double handling
        prop['type'] = 'number'
        prop['format'] = 'float'
        # -- Handling IEE 754 format
        prop['example'] = ieee(example_val)
        prop['description'] = prop_spec['description']
      when 'enum'
        prop['type'] = 'string'
        prop['enum'] = prop_spec['values'].map { |val| val['name'] }
        prop['example'] = prop_spec['values'].first['name']
      when 'capability_state'
        prop['type'] = 'array'
        prop['items'] = {
          'description' => 'A state of the vehicle',
          'type' => "object"
        }
      else
        # -- Handling object
        if prop_spec['items']
          # --- Creating a new model to be referenced
          prop_model = Hash.new
          prop_model['type'] = 'object'
          prop_model['properties'] = Hash.new
      
          prop_spec['items'].each_with_index do |prop_item_spec, idx|
            item = Hash.new
            item_example = example[prop_spec['name']].first['item']

            case prop_item_spec['type']
            when 'string'
              item['type'] = 'string'
              # --- Handling string format
              item['example'] = 'TODO' # TODO: hex_to_s(item_example[idx]['value'])
              item['description'] = prop_item_spec['description']
            when 'integer'
              item['type'] = 'number'
              item['format'] = 'integer'
              # --- Handling decimal format
              item['example'] = decimal(item_example[idx]['value'])
              item['description'] = prop_item_spec['description']
            when 'float'
              item['type'] = 'number'
              item['format'] = 'float'
              # --- Handling IEE 754 format
              item['example'] = ieee(item_example[idx]['value'])
              item['description'] = prop_item_spec['description']
            when 'enum'
              item['type'] = 'string'
              item['enum'] = prop_item_spec['values'].map { |val| val['name'] }
              item['example'] = prop_item_spec['values'].first['name']
            when 'capability_enum'
              item['type'] = 'string'
              # --- Handling enum of all capabilities
              item['enum'] = Dir.glob('../*.yml').map do |val|
                base_name = File.basename(val, '.yml')
                base_name unless exceptions['rejections'].include?(base_name)
              end.compact

              item['example'] = 'charging'
            when 'message_types_enum'
              item['type'] = 'array'
              item['items'] = {
                'description' => prop_item_spec['description'],
                'type' => 'enum',
                'enum' => []
              }

              # --- Handling enum of all message types
              item['items']['enum'] = []
              Dir.glob('../*.yml').map do |val|
                meta_cap = YAML.load_file(val)

                unless exceptions['rejections'].include?(meta_cap['name'])
                  item['items']['enum'] = item['items']['enum'] + meta_cap['message_types'].map do |msg|
                    # Ignore state resonses for clarity
                    msg['name'] unless msg['id'] == '0x01'
                  end.compact
                end
              end
              item['items']['example'] = 'get_charge_state'
            else
              puts "Found a property item with type #{prop_item_spec['type']} - skipping that.."
            end

            # --- Adding item to property
            prop_model['properties'][swagger_prop_name(prop_item_spec)] = item
          end

          prop_swagger_name = swagger_name(prop_spec['name'])

          # -- Referencing to model
          if exceptions['arrays'].include?(prop_spec['name'])
            prop['type'] = 'array'
            prop['items'] = {
              'description' => prop_swagger_name,
              '$ref' => "#/definitions/#{prop_swagger_name}"
            }
          else
            prop['description'] = prop_swagger_name
            prop['$ref'] = "#/definitions/#{prop_swagger_name}"
          end

          # -- Push model to definitions
          defs['definitions'][prop_swagger_name] = prop_model
        else
          puts "Found a property with type #{prop_spec['type']} - skipping that.."
          next
        end
      end
    end

    # -- Add property
    cap['properties'][swagger_prop_name(prop_spec)] = prop
  end

  # - Push capability
  defs['definitions'][cap_name] = cap
end

# Add additional models from exceptions conf
exceptions['definitions'].each do |model|
  # key, object
  defs['definitions'][model.first] = model.last
end

# Add permission scopes
owner_auth = Hash.new
owner_auth['type'] = 'oauth2'
# -- TODO: the URL should be added in the UI, as it's unique 
owner_auth['authorizationUrl'] = 'https://developers.high-mobility.com/hm_cloud/o/{org_oem}/oauth'
owner_auth['flow'] = 'implicit'
scopes = Hash.new

permissions_spec = YAML.load_file('../permissions/auto_api.yml')
permissions_spec['bytes'].each do |byte|
  # Skip certificate permissions (idx 1)
  if byte['idx'] != 1
    byte['bits'].each do |bit|
      scopes[bit['name']] = bit['description']
    end
  end
end

owner_auth['scopes'] = scopes

defs['securityDefinitions'] = Hash.new
defs['securityDefinitions']['owner_auth'] = owner_auth

# Store definitions
open("definitions.yaml", 'w') { |f| f.write(defs.to_yaml) }

# All done
puts "*** I think I made it.."